App.Mvc/Controllers/AuthController.cs
using App.Data.Entities;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using App.Mvc.Models;
using App.Data.Context;
using App.Data.Abstract;

namespace App.Mvc.Controllers
{
    public class AuthController : Controller
    {
       
        private readonly IRepository<CartEntity> _cartRepository;
        private readonly IRepository<UserEntity> _userRepository;
       
        public AuthController(IRepository<CartEntity> cartRepository, IRepository<UserEntity> userRepository)
        {
            _cartRepository = cartRepository;
            _userRepository = userRepository;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userRepository.Get().FirstOrDefaultAsync(u => u.Email == model.Email && u.Password == model.Password);
                if (user != null)
                {
                    var claims = new[] { new Claim(ClaimTypes.Name, user.Email) };
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid email or password");
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new UserEntity { Name = model.Name, Surname = model.Surname, Email = model.Email, Password = model.Password };
                

                var newUser = new UserEntity
                {
                    Name = model.Name,
                    Surname = model.Surname,
                    Email = model.Email,
                    Password = model.Password
                };

                _userRepository.Create(newUser);

                var defaultCart = new CartEntity
                {
                    UserId = newUser.Id,
                    CreatedAt = DateTime.Now,
                    Name = "DefaultCart"
                };
                _cartRepository.Create(defaultCart);
                return RedirectToAction("Login");
            }

            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

App.Mvc/Controllers/CartController.cs
using App.Data.Abstract;
using App.Data.Context;
using App.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace App.Mvc.Controllers
{
    [Authorize]
    public class CartController : Controller
    {

        private readonly IRepository<CartEntity> _cartRepository;
        private readonly IRepository<UserEntity> _userRepository;
        private readonly IRepository<CartItemEntity> _cartItemRepository;


        public CartController(IRepository<CartEntity> cartRepository, IRepository<UserEntity> userRepository, IRepository<CartItemEntity> cartItemRepository)
        {
            _cartRepository = cartRepository;
            _userRepository = userRepository;
            _cartItemRepository = cartItemRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var email = User.Identity.Name;

            var user = await _userRepository.Get().FirstOrDefaultAsync(u => u.Email == email);


            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var cart = await _cartRepository.Get()
                .Include(c => c.CartItems)
                .FirstOrDefaultAsync(c => c.UserId == user.Id && c.Name == "DefaultCart");

            if (cart == null)
            {
                cart = new CartEntity { UserId = user.Id, CreatedAt = DateTime.Now, Name = "DefaultCart" };
                _cartRepository.Create(cart);
            }

            return View(cart);
        }


        public async Task<IActionResult> List()
        {
            var email = User.Identity.Name;

            var user = await _userRepository.Get().Include(u => u.Carts).FirstOrDefaultAsync(u => u.Email == email);

            return View(user.Carts);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            var email = User.Identity.Name;
            var user = await _userRepository.Get().FirstOrDefaultAsync(u => u.Email == email);

            var cart = await _cartRepository.Get().Include(c => c.CartItems).ThenInclude(ci => ci.Product).FirstOrDefaultAsync(c => c.Id == id && c.UserId == user.Id);

            if (cart == null)
                return NotFound();

            decimal total = 0m;

            foreach (var item in cart.CartItems)
                total += item.Quantity * item.Product.Price;

            ViewBag.TotalPrice = total;

            return View(cart);
        }

        [HttpGet]
        public IActionResult New()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> New([FromForm] CartEntity carts)
        {
            var email = User.Identity.Name;
            var user = await _userRepository.Get().FirstOrDefaultAsync(u => u.Email == email);

            var cartName = Request.Form["cartName"]; 
            var cart = new CartEntity { UserId = user.Id, Name = cartName, CreatedAt = DateTime.Now };
            _cartRepository.Create(cart);


            return RedirectToAction("List");
        }

       

        [HttpPost]
        public async Task<IActionResult> AddToCart(int productId, int quantity, int cartId)
        {
            var email = User.Identity.Name;

            var user = await _userRepository.Get().FirstOrDefaultAsync(u => u.Email == email);

            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var cart = await _cartRepository.Get()
                .Include(c => c.CartItems)
                .FirstOrDefaultAsync(c => c.UserId == user.Id && c.Id == cartId);

            if (cart == null)
            {
                cart = await _cartRepository.Get()
                    .Include(c => c.CartItems)
                    .FirstOrDefaultAsync(c => c.UserId == user.Id && c.Name == "DefaultCart");

                if (cart == null)
                {
                    cart = new CartEntity { UserId = user.Id, CreatedAt = DateTime.Now, Name = "DefaultCart" };
                    _cartRepository.Create(cart);
                }
            }

            var cartItem = _cartItemRepository.Get()?.FirstOrDefault(ci => ci.ProductId == productId);

            
                cartItem = new CartItemEntity { CartId = cart.Id, ProductId = productId, Quantity = quantity };

                cart.CartItems.Add(cartItem);
                _cartRepository.Update(cart.Id, cart);


            return RedirectToAction("Index", "Home");
        }

    }
}

App.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - App.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/App.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">App.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> 
                        
                        @if (User.Identity?.IsAuthenticated == false)
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            
                        }
                        else if ((User.Identity?.IsAuthenticated == true))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark"  asp-controller="Cart" asp-action="List">My Carts</a>
                            </li>
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark"  asp-controller="Auth" asp-action="Logout">
                                    <span class="me-2">@User.Identity.Name</span>
                                    <span>Logout</span>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - App.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>